"""empty message

Revision ID: 80db2c8bd08c
Revises: 88d29abb832f
Create Date: 2018-04-16 11:20:41.717686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80db2c8bd08c'
down_revision = '88d29abb832f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###
